sudo: required
dist: trusty
install: git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
# debootstrap in trusty is old...
before_script:
 - GNUPGHOME=~/qubes-builder/keyrings/git gpg --recv-keys "916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA"
 - GNUPGHOME=~/qubes-builder/keyrings/git gpg --fingerprint "916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA"
 - echo '916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA:6:' | GNUPGHOME=~/qubes-builder/keyrings/git gpg --import-ownertrust
 - GNUPGHOME=~/qubes-builder/keyrings/git gpg --fingerprint "916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA"
 - sudo ln -s sid /usr/share/debootstrap/scripts/stretch
 - export VERBOSE=3
 - export DEBUG=1
#- export REPO_PROXY=http://127.0.0.1:3142
 - export CHECK_BRANCH=1
 - export BRANCH_template_whonix=master
 - export GIT_URL_template_whonix=https://github.com/adrelanos/qubes-template-whonix.git
 - env
script: ~/qubes-builder/scripts/travis-build linux-template-builder
after_success:
 - ls -l ~/qubes-builder/qubes-src/linux-template-builder/rpm/noarch
language: generic
env:
# - DISTS_VM=jessie USE_QUBES_REPO_VERSION=3.1
# - DISTS_VM=jessie+standard USE_QUBES_REPO_VERSION=3.1
# - DISTS_VM=stretch USE_QUBES_REPO_VERSION=3.1
# - DISTS_VM=jessie USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
# - DISTS_VM=jessie+standard USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
# - DISTS_VM=stretch USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - BUILDER_PLUGINS="template-whonix builder-debian" DISTS_VM=whonix-gateway USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
# - DISTS_VM=whonix-workstation USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
